resources:
  - url: /local/spinner-card.js
    type: module

title: Home
views:
  - path: default_view
    title: Home
    badges: []
    cards:
      - type: 'custom:spinner-card'
        duration_entity: input_number.spinner_duration
        mode_entity: input_select.spinner_options
        time_entity: input_datetime.spinner_time
      - type: entities
        title: Raw Entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.spinner_time
          - entity: input_select.spinner_options
          - entity: input_number.spinner_duration

